x-app-commom: &app-commom
  restart: always
  tty: true

services:
  backend:
    container_name: tcc-backend
    build:
      context: ./backend
    image: tcc/backend
    ports:
      - 5000:5000
    <<: *app-commom

  frontend:
    container_name: tcc-frontend
    build:
      context: ./frontend
    image: tcc/frontend
    ports:
      - 5173:80
    healthcheck:
      test: ['CMD', 'curl', 'http://127.0.0.1:80']
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 10s
    <<: *app-commom
