x-backend-commom: &backend-commom
  restart: always
  tty: true
  ports:
    - 5000:5000

x-frontend-commom: &frontend-commom
  restart: always
  tty: true
  ports:
    - 5173:80
  healthcheck:
    test: ['CMD', 'curl', 'http://127.0.0.1:80']
    interval: 5s
    timeout: 15s
    retries: 5
    start_period: 10s

services:
  backend:
    container_name: tcc-backend
    build:
      context: ./backend
    image: tcc/backend
    <<: *backend-commom

  frontend:
    container_name: tcc-frontend
    build:
      context: ./frontend
    image: tcc/frontend
    <<: *frontend-commom