services:
  postgres_db:
    container_name: local-database
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', $DB_NAME]
      interval: 5s
      retries: 5
    restart: always
volumes:
  postgres_db:
    driver: local
